sudo: false

language: node_js

node_js:
  - "10"

-cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - npm i -g npm@latest

install:
  - npm i

script:
  - npm run build:ci

git:
  depth: 1
