(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["common"],{

/***/ "./src/app/shared/components/basic-example/basic-example-data.component.ngfactory.js":
/*!*******************************************************************************************!*\
  !*** ./src/app/shared/components/basic-example/basic-example-data.component.ngfactory.js ***!
  \*******************************************************************************************/
/*! exports provided: RenderType_BasicExampleDataComponent, View_BasicExampleDataComponent_0, View_BasicExampleDataComponent_Host_0, BasicExampleDataComponentNgFactory */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "RenderType_BasicExampleDataComponent", function() { return RenderType_BasicExampleDataComponent; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "View_BasicExampleDataComponent_0", function() { return View_BasicExampleDataComponent_0; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "View_BasicExampleDataComponent_Host_0", function() { return View_BasicExampleDataComponent_Host_0; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "BasicExampleDataComponentNgFactory", function() { return BasicExampleDataComponentNgFactory; });
/* harmony import */ var _angular_core__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! @angular/core */ "../../node_modules/@angular/core/fesm2015/core.js");
/* harmony import */ var _dist_ng2_smart_table_ng2_smart_table_ngfactory__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../../../../../../../dist/ng2-smart-table/ng2-smart-table.ngfactory */ "../../dist/ng2-smart-table/ng2-smart-table.ngfactory.js");
/* harmony import */ var ng2_smart_table__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ng2-smart-table */ "../../dist/ng2-smart-table/fesm2015/ng2-smart-table.js");
/* harmony import */ var _basic_example_data_component__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ./basic-example-data.component */ "./src/app/shared/components/basic-example/basic-example-data.component.ts");
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 




var styles_BasicExampleDataComponent = [];
var RenderType_BasicExampleDataComponent = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵcrt"]({ encapsulation: 2, styles: styles_BasicExampleDataComponent, data: {} });

function View_BasicExampleDataComponent_0(_l) { return _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵvid"](0, [(_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵeld"](0, 0, null, null, 1, "ng2-smart-table", [], null, null, null, _dist_ng2_smart_table_ng2_smart_table_ngfactory__WEBPACK_IMPORTED_MODULE_1__["View_ɵbo_0"], _dist_ng2_smart_table_ng2_smart_table_ngfactory__WEBPACK_IMPORTED_MODULE_1__["RenderType_ɵbo"])), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵdid"](1, 573440, null, 0, ng2_smart_table__WEBPACK_IMPORTED_MODULE_2__["ɵbo"], [], { source: [0, "source"], settings: [1, "settings"] }, null)], function (_ck, _v) { var _co = _v.component; var currVal_0 = _co.data; var currVal_1 = _co.settings; _ck(_v, 1, 0, currVal_0, currVal_1); }, null); }
function View_BasicExampleDataComponent_Host_0(_l) { return _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵvid"](0, [(_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵeld"](0, 0, null, null, 1, "basic-example-data", [], null, null, null, View_BasicExampleDataComponent_0, RenderType_BasicExampleDataComponent)), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵdid"](1, 49152, null, 0, _basic_example_data_component__WEBPACK_IMPORTED_MODULE_3__["BasicExampleDataComponent"], [], null, null)], null, null); }
var BasicExampleDataComponentNgFactory = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵccf"]("basic-example-data", _basic_example_data_component__WEBPACK_IMPORTED_MODULE_3__["BasicExampleDataComponent"], View_BasicExampleDataComponent_Host_0, {}, {}, []);



/***/ })

}]);
//# sourceMappingURL=common-es2015.js.map